# Notebook de développement du modèle

Ce dataset comporte peu de données pour chaque classe (entre 60 et 100). <br>
Ainsi il faudra adapter les méthodes d'apprentissages.

## Data Management

In [20]:
import numpy as np
import pandas as pd
import os
from PIL import Image
import glob
import cv2 

In [21]:
liste_poissons=['apognon','epinephelus_marginatus','girelle_paon','pempheris_vanicolensis','sparisoma_cretense']

### Renommer les fichiers

In [22]:
'''
for espece in liste_poisson:
    root = r"data/{}".format(espece)
    print(root)
    count = 0
    for dirs, subdir, files in os.walk(root):
        for file in files:
            os.rename(root+"/"+file,root+"/{}{}.jpg".format(espece,count))
            count+=1
'''

'\nfor espece in liste_poisson:\n    root = r"data/{}".format(espece)\n    print(root)\n    count = 0\n    for dirs, subdir, files in os.walk(root):\n        for file in files:\n            os.rename(root+"/"+file,root+"/{}{}.jpg".format(espece,count))\n            count+=1\n'

### Redimmensionner les images

In [23]:
'''
for espece in liste_poisson:
    files = glob.glob('./data/{}/*'.format(espece))

    for file in files:
        img = Image.open(file)
        img_resize = img.resize((150, 100))
        root, ext = os.path.splitext(file)
        basename = os.path.basename(root)
        print(basename)
        img_resize.save(os.path.join('./data/{}/'.format(espece), basename+'.jpg'))
'''

"\nfor espece in liste_poisson:\n    files = glob.glob('./data/{}/*'.format(espece))\n\n    for file in files:\n        img = Image.open(file)\n        img_resize = img.resize((150, 100))\n        root, ext = os.path.splitext(file)\n        basename = os.path.basename(root)\n        print(basename)\n        img_resize.save(os.path.join('./data/{}/'.format(espece), basename+'.jpg'))\n"

### Verifier que les dimensions de chaque images soient bien les mêmes

In [24]:
'''
for espece in liste_poissons:
    files = glob.glob('./data/{}/*'.format(espece))
    compteur=0
    for f in files:
        im = np.array(Image.open(f))

        if im.dtype!='uint8':
            print("mauvais type"+str(compteur))
            print(im.dtype)
        if im.shape!=(100,150,3):
            print("l'image {} n'a pas les bonnes dimensions!".format(compteur))
            print(im.shape)
        compteur+=1
'''

'\nfor espece in liste_poissons:\n    files = glob.glob(\'./data/{}/*\'.format(espece))\n    compteur=0\n    for f in files:\n        im = np.array(Image.open(f))\n\n        if im.dtype!=\'uint8\':\n            print("mauvais type"+str(compteur))\n            print(im.dtype)\n        if im.shape!=(100,150,3):\n            print("l\'image {} n\'a pas les bonnes dimensions!".format(compteur))\n            print(im.shape)\n        compteur+=1\n'

### Conversion des images en niveaux de gris

In [25]:
'''
for espece in liste_poissons:
    files = glob.glob('./data/grey/{}/*'.format(espece))
    for file in files:
        img = Image.open(file).convert('L')
        root, ext = os.path.splitext(file)
        basename = os.path.basename(root)
        img.save(os.path.join('./data/grey/{}/'.format(espece), basename+'.jpg'))
'''

"\nfor espece in liste_poissons:\n    files = glob.glob('./data/grey/{}/*'.format(espece))\n    for file in files:\n        img = Image.open(file).convert('L')\n        root, ext = os.path.splitext(file)\n        basename = os.path.basename(root)\n        img.save(os.path.join('./data/grey/{}/'.format(espece), basename+'.jpg'))\n"

### Création du data frame contenant les espèces

### Normalisation

In [35]:

for espece in liste_poissons:
    i=0
    files = glob.glob('./data/grey/{}/*'.format(espece))
    for file in files:
        img=cv2.imread(file)
        norm = cv2.normalize(img,None,norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
        cv2.imwrite(os.path.join('./data/normalize/grey/{}/'.format(espece),'{}{}.jpg'.format(espece,i)),norm)
        cv2.waitKey(0)
        i+=1

        print(norm)



[[[0.20869565 0.20869565 0.20869565]
  [0.1826087  0.1826087  0.1826087 ]
  [0.17391303 0.17391303 0.17391303]
  ...
  [0.2695652  0.2695652  0.2695652 ]
  [0.32608694 0.32608694 0.32608694]
  [0.39999998 0.39999998 0.39999998]]

 [[0.21304347 0.21304347 0.21304347]
  [0.24782607 0.24782607 0.24782607]
  [0.22173911 0.22173911 0.22173911]
  ...
  [0.27826086 0.27826086 0.27826086]
  [0.28695652 0.28695652 0.28695652]
  [0.33913043 0.33913043 0.33913043]]

 [[0.19130434 0.19130434 0.19130434]
  [0.23913042 0.23913042 0.23913042]
  [0.22173911 0.22173911 0.22173911]
  ...
  [0.3217391  0.3217391  0.3217391 ]
  [0.3043478  0.3043478  0.3043478 ]
  [0.36086956 0.36086956 0.36086956]]

 ...

 [[0.27826086 0.27826086 0.27826086]
  [0.4217391  0.4217391  0.4217391 ]
  [0.44782606 0.44782606 0.44782606]
  ...
  [0.4217391  0.4217391  0.4217391 ]
  [0.4347826  0.4347826  0.4347826 ]
  [0.44347823 0.44347823 0.44347823]]

 [[0.2826087  0.2826087  0.2826087 ]
  [0.34347823 0.34347823 0.34347823]
